app/CBG/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('upload_CBG/', views.upload_CBG, name='upload_CBG'),
    path('read_CBG/', views.read_CBG, name='read_CBG'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/IOT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('', include(('CBG.urls', 'CBG'), namespace='CBG')),
    path('', include(('Main.urls', 'Main'), namespace='Main'))
]

app/Main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name= "logout"),
]

app/Main/models.py
from django.db import models

# Create your models here.

app/Main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.
class RegistrationForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

app/Main/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib import messages
from django.contrib.auth import login as login_f, authenticate, logout as logout_f
from django.contrib.auth.forms import AuthenticationForm
from CBG.models import CBG_Food_Record
import datetime
from pytz import timezone
import os

# # endpoint to render index page for all users
# def index(request):
#     if request.method == 'GET':
#         query_set = CBG_Food_Record.objects.all().order_by('Before_CBG_Uploaded_At__minute')
#         readings = []
#         measurements = []
#         foodnames = []
#         cbg_datetime = []
#         for i in query_set:
#             readings.append(i.Before_CBG_Reading)
#             readings.append(i.After_CBG_Reading)
#             measurements.append(i.Before_CBG_Measurement)
#             measurements.append(i.After_CBG_Measurement)
#             foodnames.append(i.Food_Name)
#             cbg_datetime.append(i.Before_CBG_Uploaded_At.astimezone(timezone('Asia/Singapore')).strftime("%Y/%m/%d, %H:%M"))
#             cbg_datetime.append(i.After_CBG_Uploaded_At.astimezone(timezone('Asia/Singapore')).strftime("%Y/%m/%d, %H:%M"))
#         return render(
#             request,
#             'Main/index.html',
#             context={
#                 'readings': readings,
#                 'measurements': measurements,
#                 'foodnames': foodnames,
#                 'cbg_datetime': cbg_datetime
#             }
#         )

# endpoint to render index page for all users
def index(request):
    if request.method == 'GET':
        query_set = CBG_Food_Record.objects.all().order_by('Before_CBG_Uploaded_At__minute')
        results = []
        food = []
        foodlist= []

        for i in query_set:

            each_entry = {
                'Before_CBG_Reading': i.Before_CBG_Reading, 
                'After_CBG_Reading': i.After_CBG_Reading,
                'Before_CBG_Measurement': i.Before_CBG_Measurement,
                'After_CBG_Measurement': i.After_CBG_Measurement,
                'Food_Name': i.Food_Name,
                'Food_Uploaded_At': i.Food_Uploaded_At.astimezone(timezone('Asia/Singapore')).strftime("%Y/%m/%d, %H:%M"),
                'Before_CBG_Uploaded_At': i.Before_CBG_Uploaded_At.astimezone(timezone('Asia/Singapore')).strftime("%Y/%m/%d, %H:%M"),
                'After_CBG_Uploaded_At': i.After_CBG_Uploaded_At.astimezone(timezone('Asia/Singapore')).strftime("%Y/%m/%d, %H:%M")
            }
            results.append(each_entry)


            if i.Food_Name not in foodlist:
                print(i.Food_Name)
                foodlist.append(i.Food_Name)
                each_food = {
                    'Food_Name': i.Food_Name,
                    'Food_Calorie': i.Food_Calorie,
                    'Food_Carb': i.Food_Carb,
                    'Food_Sugar': i.Food_Sugar,
                    'Food_Fibre': i.Food_Fibre
                }
                food.append(each_food)
             
        return render(
            request,
            'Main/index.html',
            context={
                'food': food,
                'results': results,
                'TELE_TOKEN': os.environ.get('TELE_TOKEN'),
                'CHAT_ID': os.environ.get('CHAT_ID'),
            }
        )

# renders registration page for all users
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login_f(request, user)
            messages.success(request, "Registration successful." )
            return redirect("Main:index")
        else:
            messages.error(request, "Unsuccessful registration.")
    else:
        form = RegistrationForm()
    return render(request, 'Main/register.html', {'form': form})

#  renders login page for all users
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login_f(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("Main:index")
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
    else:
        form = AuthenticationForm()
    return render(request, "Main/login.html", context={"form": form})

def logout(request):
	logout_f(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("Main:index")

app/Main/templates/Main/base.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Diabreezy{% endblock %}</title>
        <!-- bootstrap css -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">        
        <!-- bootstrap js -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>        
        <!-- custom css -->
        <link rel="stylesheet" href="{% static 'Main/css/style.css' %}">
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
        <!-- Chart JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.2.1/chart.umd.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-datalabels/2.2.0/chartjs-plugin-datalabels.min.js" integrity="sha512-JPcRR8yFa8mmCsfrw4TNte1ZvF1e3+1SdGMslZvmrzDYxS69J7J49vkFL8u6u8PlPJK+H3voElBtUCzaXj+6ig==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <!-- axios -->
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>    
    </head>

    <body>
        {% for message in messages %}
        <div class="container-fluid p-0">
            <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="True">&times;</span>
                </button>
                {{ message }}
            </div>
        </div>
        {% endfor %}
        {% block body %}{% endblock %}
        <script>
            $(document).ready(function() {
                // show the alert
                setTimeout(function() {
                    $(".alert").alert('close');
                }, 2000);
            });
        </script>
        {% block scripts %}{% endblock %}
    </body>
</html>

app/Main/templates/Main/login.html
{% extends 'Main/base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block body %}
<div class="container py-5">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <p class="text-center">Don't have an account? <a href="{% url 'Main:register' %}">Create an account</a>.</p>
</div>
{% endblock %}

app/Main/templates/Main/register.html
{% extends "Main/base.html" %}
{% load static %}

{% block title %}Register{% endblock %}

{% block body %}
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'Main:login' %}">login</a> instead.</p>
</div>
{% endblock %}